# Generated by Django 5.2.8 on 2025-11-27 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("column_count", models.IntegerField(blank=True, null=True)),
                (
                    "columns",
                    models.TextField(help_text="Comma-separated list of column names"),
                ),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("query_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("python_code", models.TextField(blank=True)),
                ("sql_command", models.TextField(blank=True)),
                (
                    "result_data",
                    models.TextField(blank=True, help_text="Query result as string"),
                ),
                ("has_chart", models.BooleanField(default=False)),
                (
                    "chart_image",
                    models.TextField(
                        blank=True, help_text="Base64 encoded chart image"
                    ),
                ),
                ("execution_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="query_app.datasetupload",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Query histories",
                "ordering": ["-query_date"],
            },
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
